### ISSUE TITLE
Minor Todo bugs to fix🐞 + features 🧷

### ISSUE THREAD

**Issue by FotieMConstant** [clevaway/kemeet#10]
A small list of minor bugs to tackle for any new contributor looking to shoot some bugs;

- [x] Added the Designed logo to the app and the favicon
- [ ] Remove video controls on videos
- [ ] Play sound on participant join room and on participant leave
- [ ] Add take screenshot feature, Participant should be able to take a screenshot of the meeting with all participants (Just the meeting screen, not with chat section,(Just my thought but you could suggest something✨))
- [ ] Sound effect pack for other minor interactions would be great
- [ ] Toggle chat, the participant should be able to show and hide the chat section by clicking on the toggle button which is the chat icon.
- [ ] Full-screen mode for the meeting
- [ ] Mute and unmute of mic
- [ ] Enable and Disable camera sharing with other participants in the meeting
- [ ] Dark mode 🌑
- [ ] [Suggest a feature or bug to fix below!]

Thank you for making the world a better place by contributing to **kémeet**  - _**You are the real hero**_ 🦸🏽
